let articleMode=true;let current=0;const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const snippetRegistry=[];
function blockHtml(b){if(b.type==='text')return `<section class="block"><h3>${esc(b.title)}</h3><p>${esc(b.text)}</p></section>`;
if(b.type==='call')return `<section class="callout"><h3>${esc(b.title)}</h3><p>${esc(b.text)}</p></section>`;
if(b.type==='table')return `<section class="block"><h3>${esc(b.title)}</h3><div class="table-wrap"><table><thead><tr>${b.headers.map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${b.rows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;
if(b.type==='flow')return `<section class="block"><h3>${esc(b.title)}</h3><div class="flow">${b.items.map((x,i)=>`<div class="flow-item"><b>0${i+1}</b>${esc(x)}</div>`).join('')}</div></section>`;
if(b.type==='formula')return `<section class="block"><h3>${esc(b.title)}</h3><div class="formula"><div class="expression">${esc(b.formula)}</div><p>${esc(b.text)}</p></div></section>`;
if(b.type==='code'){const n=snippetRegistry.push(b)-1;return `<section class="block"><h3>${esc(b.title)}</h3><div class="code-panel"><div class="code-head"><span>${esc(b.lang.toUpperCase())} / ${esc(b.title)}</span><button class="copy" data-copy="${n}" aria-label="Copy ${esc(b.title)}">Copy code</button></div><div class="code-context">${esc(b.context)}</div><pre tabindex="0"><code>${esc(b.text)}</code></pre></div><div class="explain-label">WHAT THE CODE DOES</div><dl class="notes">${b.notes.map(([a,c])=>`<dt>${esc(a)}</dt><dd>${esc(c)}</dd>`).join('')}</dl></section>`}}
function chapterHtml(c,i){return `<article id="${c.id}" aria-labelledby="title-${c.id}"><div class="chapter-heading"><span class="eyebrow">CHAPTER ${String(i+1).padStart(2,'0')} · ${c.time} READ</span><h2 id="title-${c.id}">${esc(c.title)}</h2><p>${esc(c.desc)}</p></div>${c.blocks.map(blockHtml).join('')}<div class="sources">READ THE PRIMARY SOURCES<br>${c.sources.map(k=>`<a href="${S[k][1]}" target="_blank" rel="noopener noreferrer">${S[k][0]}</a>`).join('')}</div></article>`}
function render(scroll=false){snippetRegistry.length=0;let part='';document.querySelector('#nav').innerHTML=chapters.map((c,i)=>{const heading=part!==c.part?`<div class="nav-group">${c.part}</div>`:'';part=c.part;return heading+`<a class="nav-link ${i===current?'active':''}" href="#${c.id}" ${i===current?'aria-current="page"':''}><span class="num">${String(i+1).padStart(2,'0')}</span><span>${esc(c.title)}</span></a>`}).join('');
document.querySelector('#content').innerHTML=articleMode?chapters.map(chapterHtml).join(''):chapterHtml(chapters[current],current);document.body.classList.toggle('article-mode',articleMode);document.querySelector('#view').textContent=articleMode?'Chapter view':'Article view';document.querySelector('#view').setAttribute('aria-pressed',articleMode);document.querySelector('#chapter-count').textContent=articleMode?'THE COMPLETE FIELDBOOK':`CHAPTER ${String(current+1).padStart(2,'0')} / 09`;document.querySelector('#pager').innerHTML=articleMode?'':`${current>0?`<button data-page="${current-1}">Previous · ${esc(chapters[current-1].title)}</button>`:'<span></span>'}${current<chapters.length-1?`<button class="next-btn" data-page="${current+1}">Next · ${esc(chapters[current+1].title)}</button>`:'<button id="finish">Read the complete article</button>'}`;
if(scroll)document.getElementById(chapters[current].id).scrollIntoView({behavior:'smooth'});}
function goHash(){const idx=chapters.findIndex(c=>c.id===location.hash.slice(1));if(idx>=0){current=idx;render(true)}else render();document.querySelector('#sidebar').classList.remove('open');document.querySelector('#menu').setAttribute('aria-expanded','false')}
window.addEventListener('hashchange',goHash);
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display='none',2500)}
async function copy(text){try{await navigator.clipboard.writeText(text);return true}catch{const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();return ok}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-copy]');if(b){const ok=await copy(snippetRegistry[Number(b.dataset.copy)].text);toast(ok?'Code copied. Paste it into VS Code.':'Copy unavailable. Select the code and copy manually.');if(ok){b.textContent='Copied';setTimeout(()=>b.textContent='Copy code',1800)}}const p=e.target.closest('[data-page]');if(p)location.hash=chapters[Number(p.dataset.page)].id;if(e.target.id==='finish'){articleMode=true;render();window.scrollTo({top:0,behavior:'smooth'})}});
document.querySelector('#view').onclick=()=>{articleMode=!articleMode;render();if(articleMode)document.getElementById(chapters[current].id).scrollIntoView({behavior:'smooth'});else window.scrollTo({top:0,behavior:'smooth'})};document.querySelector('#menu').onclick=()=>{const open=document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#menu').setAttribute('aria-expanded',open)};
function markdown(){let out='# Fine-tuning Fieldbook\n\nA practical guide to open-source language model fine-tuning.\n\nBy **Karamjeet Singh (IITG CSE)**\n\nContact: [ksn2939@gmail.com](mailto:ksn2939@gmail.com) · [+91 9123701916](tel:+919123701916)\n\nTeaching code targets the pinned dependencies in the local project. Training has not been executed by the author. The 30-example synthetic dataset is a pipeline demonstration, not evidence of model quality.\n\n';for(const c of chapters){out+=`## ${c.title}\n\n${c.desc}\n\n`;for(const b of c.blocks){out+=`### ${b.title}\n\n`;if(b.type==='text'||b.type==='call')out+=b.text+'\n\n';if(b.type==='formula')out+=b.formula+'\n\n'+b.text+'\n\n';if(b.type==='flow')out+=b.items.map((x,i)=>`${i+1}. ${x}`).join('\n')+'\n\n';if(b.type==='table')out+='| '+b.headers.join(' | ')+' |\n| '+b.headers.map(()=>'---').join(' | ')+' |\n'+b.rows.map(r=>'| '+r.join(' | ')+' |').join('\n')+'\n\n';if(b.type==='code')out+=b.context+'\n\n```'+b.lang+'\n'+b.text+'\n```\n\n**What the code does**\n\n'+b.notes.map(([a,n])=>`- **${a}:** ${n}`).join('\n')+'\n\n';}out+='Primary sources: '+c.sources.map(k=>`[${S[k][0]}](${S[k][1]})`).join(', ')+'.\n\n'}return out}
document.querySelector('#export').onclick=()=>{const u=URL.createObjectURL(new Blob([markdown()],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='fine-tuning-fieldbook.md';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Blog-ready Markdown exported.')};
const start=chapters.findIndex(c=>c.id===location.hash.slice(1));current=Math.max(0,start);render();
